name: Optimize resource pack
on: [push, workflow_dispatch]

jobs:
  packsquash:
    permissions:
      contents: write
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for full history

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = '.'
            output_file_path = './pack.zip'

      - name: Rename and Hash
        run: |
          HASH=$(sha1sum pack.zip | head -c 40)
          mv pack.zip "$HASH.zip"
          echo "$HASH" > hash.txt
          echo "PACK_FILENAME=$HASH.zip" >> $GITHUB_ENV

      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Resource Pack Build ${{ github.run_number }}
          files: |
            ${{ env.PACK_FILENAME }}
            hash.txt
