name: Optimize resource pack
on: [push, workflow_dispatch]

jobs:
  packsquash:
    permissions:
      contents: write # Restricted permissions for better security
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Only fetch the latest commit

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = '.'
            output_file_path = './pack.zip'

      - name: Generate Hash
        id: vars
        run: |
          HASH=$(sha1sum pack.zip | head -c 40)
          echo "pack_hash=$HASH" >> $GITHUB_ENV
          echo $HASH > hash.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # Use a timestamp to ensure every build has a unique release
          tag_name: build-${{ github.run_number }}
          name: Resource Pack Build ${{ github.run_number }}
          body: "SHA-1 Hash: ${{ env.pack_hash }}"
          files: |
            pack.zip
            hash.txt
